apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: hello-fun-app
spec:
  source:
    git:
      ref:
        branch: main
      url: ssh://git@github.com/msrinivasssa/priv-java-app.git